# 基础镜像
FROM redis
# author
MAINTAINER zhao

# 挂载目录
VOLUME /home/zhao/redis
# 创建目录
RUN mkdir -p /home/zhao/redis
# 指定路径
WORKDIR /home/zhao/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/zhao/redis/redis.conf
