version : '3.8'
networks:
  my_network:
    driver: bridge
services:
  zhao-nacos:
    container_name: zhao-nacos
    image: nacos/nacos-server
    networks:
      - my_network
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - zhao-mysql
  zhao-mysql:
    container_name: zhao-mysql
    image: mysql:5.7
    networks:
      - my_network
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'zhao-cloud'
      MYSQL_ROOT_PASSWORD: '123456'
  zhao-redis:
    container_name: zhao-redis
    image: redis
    networks:
      - my_network
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/zhao/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/zhao/redis/redis.conf
  zhao-nginx:
    container_name: zhao-nginx
    image: nginx
    networks:
      - my_network
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/zhao/projects/zhao-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - zhao-gateway
  zhao-gateway:
    container_name: zhao-gateway
    networks:
      - my_network
    environment:
      NACOS_HOST: zhao-nacos
    build:
      context: ./zhao/gateway
      dockerfile: dockerfile
    ports:
      - "7573:7573"
    depends_on:
      - zhao-redis
  zhao-auth:
    container_name: zhao-auth
    networks:
      - my_network
    environment:
      NACOS_HOST: zhao-nacos
    build:
      context: ./zhao/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - zhao-redis
  zhao-modules-system:
    container_name: zhao-modules-system
    networks:
      - my_network
    environment:
      NACOS_HOST: zhao-nacos
    build:
      context: ./zhao/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
    depends_on:
      - zhao-redis
      - zhao-mysql
  zhao-modules-gen:
    container_name: zhao-modules-gen
    networks:
      - my_network
    environment:
      NACOS_HOST: zhao-nacos
    build:
      context: ./zhao/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
    depends_on:
      - zhao-mysql
  zhao-modules-job:
    container_name: zhao-modules-job
    networks:
      - my_network
    environment:
      NACOS_HOST: zhao-nacos
    build:
      context: ./zhao/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
    depends_on:
      - zhao-mysql
  zhao-modules-file:
    container_name: zhao-modules-file
    build:
      context: ./zhao/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
      - ./zhao/uploadPath:/home/zhao/uploadPath
  zhao-visual-monitor:
    container_name: zhao-visual-monitor
    networks:
      - my_network
    environment:
      NACOS_HOST: zhao-nacos
    build:
      context: ./zhao/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
