# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER zhao

# 挂载目录
VOLUME /home/zhao
# 创建目录
RUN mkdir -p /home/zhao
# 指定路径
WORKDIR /home/zhao
# 复制jar文件到路径
COPY ./jar/zhao-auth.jar /home/zhao/zhao-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","zhao-auth.jar"]